replicaCount: 1

image:
  repository: poornima2208/go-web-app-main
  pullPolicy: IfNotPresent
  tag: "v1"

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific